README.md

The beamer package of my distribution does not provide `beamerthememetropolis.sty`, so I had to install it manually.

Add Metropolis beamer theme to installation requirements

---

filters/hugo.lua

return empty para instead of empty list, which would turn up as html comment in the result

fix hugo filter

---

filters/hugo.lua
filters/tex.lua

- Web: Emit custom shortcode `img`
- Web: Use parameter `web_width` with higher precedence as `width`
- Slides: Remove parameter `web_width` if present
see https://github.com/PM-Dungeon/PM-Lecture/issues/129

Images: Rework handling of images (slides, web)

---

filters/extract_filewise.lua
filters/extract_summary.lua

Add two pandoc filters
- `filewise_pass.lua`: extract the lecture-title and weight from meta block of each `.md` file; store path of lecture in attribute (for association with `_index.md` file)
- `summary_pass.lua`: sorts all topics, chapters and slides based on path and weight-attribute

Add filters for extracting the structure of a markdown-based lecture

---

filters/hugo.lua

The "button" shortcode in Hugo-Re-Learn-Theme seems to be improved in 5.x, so let's use the original button (again). Thus the "hugo.lua" filter will emit code using the original shortcode.

[HUGO] Re-Learn-Theme 5.x: emit original 'button' shortcode instead of custom shortcode

---

filters/hugo.lua

Hugo Re-Learn-Theme 5.x supports MathJax natively. Inline and block math should
be encapsulated in a provided 'math' shortcode.

[HUGO] emit 'math' shortcode instead of span/div

---

filters/hugo.lua

Enables a key/value parameter `href` in span `bsp`. 
Examples: 
- Old behaviour (still valid): `[Get Hugo]{.bsp}` 
- New behaviour: `[Get Hugo]{.bsp href="https://gohugo.io/"}`
Lua filter: 
- TeX: `tex.lua`: `\bsp{Get Hugo}` (both cases)
- Hugo: `hugo.lua`:
- Old behaviour: `<div style="text-align: right;">{{% button style="btn-crossreference" href="" %}}Get Hugo{{% /button %}}</div>` 
- New behaviour: `<div style="text-align: right;">{{% button style="btn-crossreference" href="https://gohugo.io/" %}}Get Hugo{{% /button %}}</div>`
see also https://github.com/Programmiermethoden/PM-Lecture/issues/620

Hugo: Add key/value parameter "href" to shortcode "button"

---

defaults/hugo.yaml
defaults/slides.yaml
filters/hugo.lua
filters/tex.lua
hugo/hugo-lecture/layouts/shortcodes/img.html

In Pandoc-Markdown gibt es zwei Typen von Abbildungen: "Images" (ohne Caption) und "Figures" (mit Caption). Für das Anpassen der Größe können in Pandoc-Markdown Attribute verwendet werden. (https://pandoc.org/MANUAL.html#images)
Das Hugo Relearn Theme unterstützt eigentlich nur "Images", d.h. Abbildungen mit Caption sind nicht vorgesehen. Die Skalierung erfolgt über einen URL-Parameter. Abbildungen werden mit einer "Lightbox" dargestellt - hier kann man auf die Abbildung draufklicken und erhält dann die Abbildung in Vollansicht. (https://mcshelby.github.io/hugo-theme-relearn/cont/markdown/index.html#images) 
Prinzipiell unterstützt Hugo (und das Relearn Theme) Mehrsprachigkeit. Bei Abbildungen werden diese allerdings nur im Pfad der Default-Sprache abgelegt, für die Sprachvarianten müssen …

[Hugo] Fix image handling 

---

hugo/hugo-lecture/layouts/partials/quizzes.html

[Partials] Quizzes: Use shortcodes/notice.html from Relearne theme

---

hugo/hugo-lecture/layouts/partials/outcomes.html

[Partials] Outcomes: Use shortcodes/notice.html from Relearne theme

---

hugo/hugo-lecture/layouts/partials/assignments.html
hugo/hugo-lecture/layouts/partials/outcomes.html
hugo/hugo-lecture/layouts/partials/quizzes.html

[Partials] Assignments: Use shortcodes/notice.html from Relearne theme

---

hugo/hugo-lecture/layouts/partials/bib.html

[Partials] Bib: Use shortcodes/notice.html from Relearne theme

---

hugo/hugo-lecture/layouts/partials/archetypes/lecture-cg/article.html
hugo/hugo-lecture/layouts/partials/challenges.html

Wiedereinführung von Challenges und Aktivierung im `lecture-cg`-Archetypen.
Vorteile:

[Partials] Challenges: Use shortcodes/notice.html from Relearne theme

---

hugo/hugo-lecture/layouts/partials/archetypes/lecture-bc/article.html
hugo/hugo-lecture/layouts/partials/archetypes/lecture-cg/article.html
hugo/hugo-lecture/layouts/partials/archetypes/lecture-cy/article.html
hugo/hugo-lecture/layouts/partials/attachments.html
hugo/hugo-lecture/layouts/partials/tldr.html
hugo/hugo-lecture/layouts/partials/videos.html

Splitte TLDR auf in "TLDR", "Videos", "Attachments": Das reduziert komplexere Abfragen durch mind. drei verschiedene Anwendungsfälle und erlaubt zusätzlich den Einsatz unterschiedlicher Notice-Boxen/-Farben/-Icons.
Vorteile:
fixes https://github.com/Programmiermethoden/PM-Lecture/issues/614

[Partials] TLDR: Use shortcodes/notice.html from Relearne theme

---

hugo/hugo-lecture/layouts/partials/menu-footer.html

Initially, it seemed like a good idea to hard wire the CC BY-SA 4.0 directly in the menu footer.
But since pandoc-lecture is now also used for other projects, each project has to define this for itself.

Hugo: Remove hardcoded license from menu footer

---

filters/hugo.lua

Initially we used some custom css styling (background, text color) for the `showme` div, which is replaced by the `expand` shortcode.
However, this does not work well in dark mode. This PR removes the custom styling for the `showme` div / `expand` shortcode.

hugo.lua: remove custom background for showme/expand

---

filters/hugo.lua

Using a `notice` shortcode for the previous `cbox` div/environment seemed like a good idea. However, a `notice` always goes across the entire width of the page, which is somewhat annoying. Furthermore, only the heading is highlighted with a strong colour, the actual box is rather discreet. The `button`, on the other hand, is only as wide as the text, and it uses the eye-catching colour for the entire box.
This PR replaces the "cbox"-div/environment with a centered `button` shortcode.

hugo.lua: replace `cbox` div with centered `button` shortcode

---

hugo/hugo-lecture/layouts/partials/archetypes/assignment/article.html
hugo/hugo-lecture/layouts/shortcodes/schedule.html

Ursprünglich war es ganz nett, die Worte "Punkte: " und "Abgabe: " automatisch aus dem YAML bzw. dem Schedule ableiten zu können und nicht immer extra hinschreiben zu müssen. Durch verschiedene Lehrveranstaltungen sind nun aber unterschiedliche Bedürfnisse entstanden, so dass dies aus dem Shortcode und dem Archetype entfernt wird.
Man muss also jetzt im `data/schedule.yaml` jetzt schreiben:
```yaml
-   week: "W12 (23. Juni)"
assignment:
-   topic: "b05b"
due: "Abgabe: Do, 22.06."
```
und in den Aufgabenblättern im YAML-Header:
```yaml
points: "15 Punkte"
```
---
Bisher: 
`data/schedule.yaml`:
```yaml
-   week: "W12 (23. Juni)"
assignment:
-   topic: "b05b"
due: "Do, 22.06."
```
Aufgabenblätter im YAML-Header:
```yaml
points: "15"
```

[Clean-Up] Remove extra words in due date and points (schedule shortcode, assignments archetype)

---

Makefile

Just in case. We usually use this via a GitHub action or locally in a Docker container. But if someone insists on using this locally (without Docker) and already has Pandoc, Hugo and TexLive installed locally, they can use the new target `install_scripts_locally` to easily install the scripts in Pandoc-Lecture and Relearn Hugo to `${HOME}/.local/share/pandoc/`.

Makefile: add install target to allow for easier local installation of pandoc-lecture and relearn theme (scripts only)

---

docker/install-packages-ubuntu.sh

package "software-properties-common" is not really needed ...
to fix possible certificate errors when running wget on https urls we just need the package "ca-certificates". 
"software-properties-common" includes "ca-certificates", but also python and several other packages not needed here.

[Docker] remove package "software-properties-common"

---

docker/install-packages-ubuntu.sh

package "build-essential" is not really needed. it contains "make", but also gcc and several other packages not needed here.

[Docker] remove package "build-essential"

---

docker/install-packages-ubuntu.sh

package "graphviz" is used to convert .dot files to .png or .svg during the compilation of the lecture material.
you can argue whether the creation of the .png files from the .dot sources really has to happen during the build process or whether you should just commit the .png files associated with a .dot file directly to the repo when creating the .dot file ...

[Docker] add package "graphviz"

---

action.yml

wow, just installing **graphiz** inside the ubuntu runner will increase the **setup time** for the base of this action **_from 2s to 25s_**! since this was already open for discussion, removing this step from the action for the time being ...

[Action] remove installing additional Ubuntu packages (graphviz)

---

action.yml
docker/install-packages-ubuntu.sh
docker/install-texlive-extra.sh
docker/install-texlive.sh

use `apt-get clean && apt-get update` instead of `apt-get update` to avoid errors while fetching packages from server
(see also https://serverfault.com/questions/690639/api-get-error-reading-from-server-under-docker)

[Action] use "apt-get clean"

---

README.md
action.yaml
docker/Dockerfile
docker/download-hugo.sh
docker/download-pandoc.sh
docker/install-hugo.sh
docker/install-pandoc.sh

For some reason lost in history, the download and install for both Pandoc and Hugo were split into two separate steps. Since I can't seem to summon enough imagination for this schism, this PR merges the download script with the install script for both tools.

Pandoc/Hugo: Merge download script into install scripts

---

hugo/hugo-lecture/layouts/shortcodes/schedule.html

This shortcode can be used without an additional option, i.e. like `{< schedule >}`. This will evaluate the schedule in `data/schedule.yaml`. 
To allow different schedules in joint lectures, this PR introduces the optional `file` option to specify the file name of the schedule, i.e. like `{< schedule file="schedule_hsbi" >}}`. In this example, the schedule is generated from `data/schedule_hsbi.yaml`. 
Here is an example of use:
```markdown
```{=markdown}
{{< tabs >}}
{{< tab title="ALT" >}}
{{< schedule >}}
{{< /tab >}}
{{< tab title="TDU" >}}
{{< schedule file="schedule_tdu" >}}
<b>Hinweis</b>: Abgabe der Hausaufgaben bis jeweils XX:XX Uhr (TR), Deadline für das Feedback je bis XX:XX Uhr (TR) am angegebenen Tag (jeweils im Google Classroom).
{{< /tab >}}
{{< tab title="HSBI" >}}
{{< …

[Hugo] add file option to schedule shortcode

---

hugo/hugo-lecture/layouts/partials/assignments.html
hugo/hugo-lecture/layouts/partials/attachments.html
hugo/hugo-lecture/layouts/partials/bib.html
hugo/hugo-lecture/layouts/partials/challenges.html
hugo/hugo-lecture/layouts/partials/outcomes.html
hugo/hugo-lecture/layouts/partials/quizzes.html
hugo/hugo-lecture/layouts/partials/tldr.html
hugo/hugo-lecture/layouts/partials/videos.html

According to https://mcshelby.github.io/hugo-theme-relearn/basics/migration/#5180 (see also https://github.com/McShelby/hugo-theme-relearn/issues/595 and https://github.com/McShelby/hugo-theme-relearn/pull/578) we have to use the parameter 'page' now instead of 'context'. Annoying. We really should switch to mdBook :/

[Hugo] fix usage of notice shortcode (from Relearn theme) in partials - API change

---

defaults/slides.yaml

Slide defaults (Beamer): It's been a long time now, so everyone should be using the current commands and divs/spans. Let's clean it up a bit and remove the call to `deprecated.lua`.

[Filter] remove deprecated filter from slides default

---

filters/hugo_rewritelinks.lua
filters/test filter/Makefile
filters/test filter/expected_rewritelinks1.native
filters/test filter/expected_rewritelinks2.native
filters/test filter/expected_rewritelinks3.native
filters/test filter/expected_rewritelinks4.native

This is the second part of #115: Add a filter, that
- transforms all 'readme.md' into '_index.md', any other Markdown file 'file.md' will be transformed into 'file/_index.md' (see 'hugo_makedeps.lua')
- will adapt the image sources and the link targets in a Markdown file so that Hugo can build a web page from it

[Filter] add rewritelinks filter: transform image src and link targets in markdown files (recursively)

---

demo/hugo-lecture/readme.md
demo/hugo-lecture/subdir/file-d.md
filters/hugo_makedeps.lua
filters/test filter/expected_makedeps1.native
filters/test filter/expected_makedeps2.native
filters/test filter/expected_makedeps3.native
filters/test filter/expected_makedeps4.native
filters/test filter/expected_rewritelinks1.native
filters/test filter/expected_rewritelinks2.native
filters/test filter/expected_rewritelinks3.native
filters/test filter/expected_rewritelinks4.native
filters/test filter/readme.md
filters/test filter/subdir/file-d.md

This changes will allow references to files up the directory structure, i.e. something like `[foo](../../foo.md)` should work now.
We use a little trick to achieve this behaviour: When evaluating a link, let Pandoc change the working directory to the link path. This will resolve all `../` (if possible) and we can then ask Pandoc for the current working directory (absolute path) and compare this to the absolute path to the project directory to get a relative path to our file ...

[Filter] change makedeps to allow '../' in paths

---

filters/hugo_makedeps.lua

When analysing a document, all links to local Markdown files are queued for later processing. After visiting this document, the links (old and new) to this document are saved in another data structure (list of all links).
To avoid analysing the same document multiple times, a check is made in the list beforehand (this corresponds to the "colouring" (labelled as explored) of nodes in breadth-first search).
This PR introduces an additional improvement: The links found during the analysis of a document are only added to the queue if they have never been in it before (dynamic programming).

[Filter] improve makedeps to reduce build time

---

filters/include-mdfiles.lua
filters/test filter/Makefile
filters/test filter/expected_inludemd.native
filters/test filter/subdir/file-d.md
filters/test filter/summary.md

include-mdfiles.lua – filter to include local Markdown files via links
```
for each link to local Markdown file in start document:
(1) read file
(2) "fix" links to local images, i.e. prepend include path
(3) process links to local Markdown files in paragraphs and include content (recursively)
- foreach Para:
- prepare new empty block list (result), add new current block (empty Para)
- foreach inline in current Para:
- if not link: append inline to current block's content
- if link:
- read link.target (file), process content and append resulting blocks to block list
- add new current block (empty Para) for remaining inlines of current block
- return block list to replace current Para
```
**warning: this won't handle endless recursion!**

[Filter] add filter to include local Markdown file via Markdown links in paragraphs

---

filters/hugo_makedeps.lua
filters/include-mdfiles.lua

Credits: Work on 'include-mdfiles.lua' and 'hugo_makedeps.lua' was partially inspired by some ideas shared in "include-files" (https://github.com/pandoc/lua-filters/blob/master/include-files/include-files.lua, by Albert Krewinkel (@tarleb), license: MIT). The 'include-mdfiles.lua' and 'hugo_makedeps.lua' filter have been developed by us from scratch and is neither based on nor contains any third-party code.

[Filter] add credits to 'include-files' (makedeps, include-md)

---

filters/include_mdfiles.lua
filters/test/Makefile

For all filters we usually use underscores, but in 'include_mdfiles.lua' we accidentally used a dash. This PR harmonises the naming and renames 'include-mdfiles.lua' to 'include_mdfiles.lua'.

[Filter] Harmonise filter names: Rename 'include-mdfiles.lua' to 'include_mdfiles.lua'

---

filters/hugo_makedeps.lua
filters/hugo_rewritelinks.lua
filters/include_mdfiles.lua
filters/test/Makefile
filters/test/expected_makedeps2.native
filters/test/expected_makedeps5.native
filters/test/expected_makedeps6.native

this changes should enable something like `pandoc -L hugo_makedeps.lua -t markdown subdir/leaf/readme.md`.
fixes #141

[Filter] refactor and allow 'hugo_makedeps.lua' to work with files in subdirs

---

filters/hugo_rewritelinks.lua
filters/test/Makefile
filters/test/expected_rewritelinks5.native

the makedeps filter allows "warping", i.e. to remove folders from the generated target path. 
rewrite needs to do the same when dealing with "readme.md" - here we replace the file name with the name of the parent folder. this must not be a "warped" folder!
this pr fixes this.
fixes #147

Filter: rewritelinks to support warping

---

examples/hugo-lecture/Makefile

the metadata 'warp' need to be used for makedeps filter as well as for rewrite filter ...
addendum to #148

Filter: fix Makefile for Hugo example

---

docker/install-pandoc.sh

see https://github.com/jgm/pandoc/issues/9014

Pandoc: downgrading to 3.1.6.1 due to issues in URL handling in 3.1.6.2

---

examples/hugo-lecture/Makefile

Sometimes the calculated paths and targets (web/pdf vs. tex and/or dot) overlap, so the wrong target springs into action. We do need the tex and dot targets only in certain cases to produce a .png from a .dot or .tex - but this will be done manually. So disabling these auxiliary targets will avoid those mismatches ...

Examples: disable tex and dot target per default

---

filters/hugo_makedeps.lua
filters/test/expected_makedeps1.native
filters/test/expected_makedeps3.native
filters/test/expected_makedeps4.native
filters/test/expected_makedeps5.native
filters/test/expected_makedeps7.native
filters/test/expected_makedeps8.native

When analysing the current file, if a link is to be placed in the queue, first place all landing pages on the path to this file in the queue. 
This way, all intermediate landing pages are taken into account and cannot be missing later when the web page is created. Moreover, the order of the landing pages no longer depends directly on the links in the sub-files. 
If the start file was 'a/b/readme.md' and we want to enqueue the link 'a/b/c/d/foo.md', then we have to enqueue 'c/readme.md' and 'c/d/readme.me' first so that the order is correct. However, we must not take into account the partial path 'a/b/' because otherwise we would go back over the level of the start file. (This can happen, however, if links in the analysed files go back too far).
fixes #153

Filter: makedeps: enqueue _all_ intermediate landing pages and do this earlier in the process

---

filters/hugo.lua
filters/test/Makefile
filters/test/codeblocks.md
filters/test/expected_codeblocks.native

In order to get proper syntax highlighting when using Hugo, 
- remove attributes from codeblocks, and 
- remove classes and attributes from inline code.
---
Examples:
``` {.haskell size="tiny"}
class Monad m where
(>>=) :: m a -> (a -> m b) -> m b
return :: a -> m a
```
and 
`void`{.c}
would not be recognised by Hugo. Thus this PR introduces some preprocessing and the `hugo.lua` filter will emit
``` haskell
class Monad m where
(>>=) :: m a -> (a -> m b) -> m b
return :: a -> m a
```
and 
`void`
---
fixes #83

Filter: remove attributes from code blocks (hugo)

---

filters/hugo.lua
filters/test/Makefile
filters/test/bsp_span.md
filters/test/expected_bsp_span.native

if we use the bsp span with an url, we should emit an interactive button shortcode. otherwise let's use a non-interactive badge shortcode to avoid confusion ...

Filter: fix hugo filter for bsp span

---

filters/hugo.lua
filters/test/Makefile
filters/test/cbox_div.md
filters/test/expected_cbox_div.native

We've been using a `button` shortcode as substitute for our `cbox` div/environment. However, those buttons suggest users to be interactive, which is not the case here. So let's switch to non-interactive `badge` shortcodes now.

Filter: fix hugo filter for cbox div

---

filters/hugo.lua
filters/test/Makefile
filters/test/expected_showme_div.native
filters/test/showme_div.md

previously: 
``` markdown
::: showme
A simple text to be centred and accentuated
:::
```
now also allowed:
``` markdown
::: {.showme title="Hello **World**"}
A simple text to be centred and accentuated
:::
```

Filter: allow a 'title' key/value pair in 'showme' div (hugo)

---

filters/hugo_rewritelinks.lua
filters/test/expected_rewritelinks1.native
filters/test/expected_rewritelinks2.native
filters/test/expected_rewritelinks3.native
filters/test/expected_rewritelinks4.native
filters/test/expected_rewritelinks5.native

see https://github.com/McShelby/hugo-theme-relearn/issues/681#issuecomment-1754767292: 
> So, the take away for me is that I have to **use the `%` format instead of the `<` format** because the way Hugo handles things internally. Additionally, I want to **use `relref` instead of `ref`**, because I want to generate an internal link with the `ref`.

Filter: fix hugo-rewrite

---

examples/hugo-lecture/hugo_conf.yaml

Generating the hugo-website example will fail when  `params.author` is used instead of `params.author.name`. See here:
https://mcshelby.github.io/hugo-theme-relearn/basics/migration/#5230

Examples: fix hugo-lecture author.name parameter

---

examples/hugo-lecture/subdir/leaf/readme.md
examples/hugo-lecture/subdir/readme.md
hugo/hugo-lecture/archetypes/chapter.md
hugo/hugo-lecture/archetypes/lecture-bc.md
hugo/hugo-lecture/archetypes/lecture-cg.md
hugo/hugo-lecture/archetypes/lecture-cy.md
hugo/hugo-lecture/layouts/shortcodes/schedule.html

this should prepare us for Relearn 5.24.0 - `menuTitle` being deprecated
(see https://github.com/McShelby/hugo-theme-relearn/issues/714)

Hugo: replace 'menuTitle' w/ 'linkTitle'

---

docker/install-relearn.sh

waiting because of https://github.com/McShelby/hugo-theme-relearn/issues/773: **need to replace `menuTitle` with `linkTitle` in all documents** before pushing this update

relearn: bump version to v5.24.1 (#233)

---

docker/install-hugo.sh

v0.123 startet to handle the baseURL wrong - local images won't be resolved properly
see https://github.com/McShelby/hugo-theme-relearn/issues/805

hugo: REVERT version back to v0.122.0
